---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/hstr.yml
    - import_tasks: tasks/jetbrains-toolbox.yml
    - import_tasks: tasks/cleanup.yml

