---
- name: Add an apt key for vscode repo
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Add apt repo for vscode
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
    update_cache: true
- name: install vscode
  apt:
    name: code

