---
- name: Install zsh
  apt:
    name: zsh
    update_cache: yes
- name: Install Oh-My-Zsh
  become: yes
  become_user: "{{ user }}"
  shell:
    cmd: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
    creates: /home/{{ user }}/.oh-my-zsh/oh-my-zsh.sh
- name: Set zsh as default shell
  command:
    cmd: chsh -s /usr/bin/zsh {{ user }}

